### ISSUE TITLE
Configure jobConfigHistory with sane default

### ISSUE THREAD

**Issue by mbarbero** [eclipse-cbi/jiro#15]
* Number of history entries to keep: 500
* Max number of days to keep history entries: 60
* Max number of history entries to show per page: 12
* Do not save duplicate history: unticked

**Comment by fredg02** [comment]
> Do not save duplicate history: unticked

@mbarbero so you want to save duplicate history? I guess you meant the opposite that this checkbox should be checked :ballot_box_with_check: , right?

**Comment by mbarbero** [comment]
> > Do not save duplicate history: unticked
> 
> @mbarbero so you want to save duplicate history? I guess you meant the opposite that this checkbox should be checked ☑️ , right?

IIRC, back in the days you were willing to not save dups as otherwise you just loose actual changes very fast. I'm fine with whatever you think is best :D

**Comment by fredg02** [comment]
:see_no_evil: :man_facepalming:
