### ISSUE TITLE
Please remove gerrit plugin from OpenMQ Jenkins instance

### ISSUE THREAD

**Issue by pzygielo** [eclipse-cbi/jiro#194]
Gerrit is not utilized in the project and the plugin does not work
![openmq-gerrit](https://user-images.githubusercontent.com/11896137/148050206-971a69bb-c2a9-4e5f-b457-97279a3ff9cb.png)
![openmq-gerrit-error](https://user-images.githubusercontent.com/11896137/148050333-531dfa9a-760f-4d07-9ebf-6709f08eb86a.png)

**Comment by mbarbero** [comment]
For historical reasons, we are bundling the gerrit trigger plugin by default on all Jenkins instances and we currently have no mean to remove a plugin defined at this level. This enhancement is currently tracked in #59.

**Comment by fredg02** [comment]
I have disabled the Gerrit trigger plugin, which should achieve the same result.

**Comment by pzygielo** [comment]
Thank you.
