### ISSUE TITLE
OMR: Permissions lost for our infra team

### ISSUE THREAD

**Issue by AdamBrousseau** [eclipse-cbi/jiro#199]
Possibly related #145 

Seems our infra team have lost permissions on omr jenkins

![image](https://user-images.githubusercontent.com/6430052/153451043-534a0a06-6f24-40e7-b799-47e3124a6746.png)

@rajdeepsingh1 
@jdekonin 
@AdamBrousseau 

https://github.com/eclipse-cbi/jiro/blob/master/instances/technology.omr/config.jsonnet

**Comment by fredg02** [comment]
I'm on it.

**Comment by AdamBrousseau** [comment]
Looks good. Thanks, Fred.
