### ISSUE TITLE
Need Docker plugin in OMR Jenkins

### ISSUE THREAD

**Issue by babsingh** [eclipse-cbi/jiro#214]
OMR is planning to launch PR builds in Docker containers: https://github.com/eclipse/omr/pull/6525.

In order achieve the above goal, OMR needs to have the Docker plugin in its Jenkins pipeline.

**Comment by babsingh** [comment]
fyi @AdamBrousseau @jdekonin

**Comment by mbarbero** [comment]
We don't support docker plugin in Jenkins as it would require DoD in our current, which is a major security issue. You can run pipeline in custom container though, as described in https://wiki.eclipse.org/Jenkins#Custom_container. Note that the container must be build and publish beforehand.

**Comment by babsingh** [comment]
> it would require DiD in our current, which is a major security issue

@mbarbero Can you provide a reference which explains why DiD is a major security issue? I did not find any direct references to `Docker in Docker` during my online search.

**Comment by mbarbero** [comment]
https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/
https://book.hacktricks.xyz/linux-hardening/privilege-escalation/docker-breakout/docker-breakout-privilege-escalation
https://www.trendmicro.com/en_us/research/19/l/why-running-a-privileged-container-in-docker-is-a-bad-idea.html

We don't allow containers on our infrastructure to run as root, and we have strict SELinux, AppArmor, and other security measures that prevents CI workload from using any of the solutions like DinD or mounting the docker socket inside the container.

**Comment by AdamBrousseau** [comment]
@mbarbero Would those concerns only apply if we were running our own container on the Controller node though? If we run a container on another worker node would there still be a security concern?

**Comment by mbarbero** [comment]
those concerns are only valid for our infra 🤦 Sorry about forgetting that OMR runs its jobs on their own node. Will install the docker plugin shortly

**Comment by mbarbero** [comment]
Plugin has been installed.

**Comment by mbarbero** [comment]
Done with https://github.com/eclipse-cbi/jiro/commit/ebab7beeaecdd90cf9d212425bf0cd508ba7320c

**Comment by mbarbero** [comment]
Sorry, this one slipped through the cracks. I'm adding the `docker-workflow` plugin right now

**Comment by mbarbero** [comment]
Done with 1d9fbf3a4de4cb4455ecf104fbead63ede03becc

Thanks for your patience on this one.

**Comment by AdamBrousseau** [comment]
Thanks, Mikaël

**Comment by babsingh** [comment]
Confirming that it works.
