### ISSUE TITLE
OMR: Many machines offline "Script not approved"

### ISSUE THREAD

**Issue by AdamBrousseau** [eclipse-cbi/jiro#253]
All our machines which connect using an "ssh command" rather than the standard ssh plugin are offline.

I assume because of this change
https://github.com/eclipse-cbi/jiro/pull/249

Not sure why this isn't automatic.

cc @fredg02

**Comment by fredg02** [comment]
Scripts have been approved. Most agents are back online.

**Comment by AdamBrousseau** [comment]
Thanks Fred. Confirmed the others are different issues I need to follow up on.
