### ISSUE TITLE
Change default timezone  from `America/Toronto` to UTC-0 to align with docker image timezone

### ISSUE THREAD

**Issue by heurtematte** [eclipse-cbi/jiro#285]
The Jiro default timezone is `America/Toronto` set in code  [here](https://github.com/eclipse-cbi/jiro/blob/master/templates/config.libsonnet#L29)

The main problem with this setting is when it comes to deal with job based on a docker image with a different timezone.
 So there is a difference between the UI and the job log generated by the docker image, which can quickly lead to confusion.

I.E: jenkins UI with job #46 started at 07:28
![image](https://github.com/eclipse-cbi/jiro/assets/8045662/54526252-51bb-43af-a58b-ff68444999c6)

Job log start at: 13:28
![image](https://github.com/eclipse-cbi/jiro/assets/8045662/279bc26c-25a6-4bfc-b132-333ff467540a)

It might be great to align the jenkins timezone with something more in common, and understandable by all like UTC-0 with no DST.

**Comment by fredg02** [comment]
This is caused by the configuration of the timestamps plugin:
![image](https://github.com/eclipse-cbi/jiro/assets/605957/7428d374-3c53-4dba-a2bd-7a69b861b2a8)
If you deactivate the "Use browser timezone" checkbox in the console log, the timezones in the build history and in the console log match.

Since most of our servers are physically located in the EST/EDT timezone, I'd recommend that we stick to that.

**Comment by pstankie** [comment]
I think we should re-evaluated changing default timezone to UTC.

This is how it looks with "default" TZ set in Jenkins:
<img width="548" alt="Screenshot 2023-07-31 at 10 41 10" src="https://github.com/eclipse-cbi/jiro/assets/6886449/f07eeac7-27e6-4082-a670-87fd2bdc7c68">
As you can see, even in the same dashboard times are different.

**Comment by fredg02** [comment]
To be honest, I never noticed that and so it never bothered me. I would consider this a bug in Jenkins, but not a reason to abandon timezones. :wink:

**Comment by fredg02** [comment]
Related bug:
* https://issues.jenkins.io/browse/JENKINS-70175
